#!/bin/bash

#################################
#                               #
# Created by Sniper for PAC-man #
#                               #
#################################

VERSION=0.8
BUILD=8

if [ -e ~/.pac/username ]
then
   USER=$(cat ~/.pac/username)
else
   echo "Please enter your gerrit username:"
   read USER
   mkdir ~/.pac
   echo $USER > ~/.pac/username
   USER=$(cat ~/.pac/username)
   echo "Your new gerrit username is: $(cat ~/.pac/username)"
fi

if [ -e ~/.pac/branch ]
then
   BRANCH=$(cat ~/.pac/branch)
else
   echo "Please enter the branch you want to upload to (ex. cm-10.2):"
   read BRANCH
   echo $BRANCH > ~/.pac/branch
   BRANCH=$(cat ~/.pac/branch)
   echo "Your new current branch is: $(cat ~/.pac/branch)"
fi


TYPE="$1"
PROJECT=$(grep PAC-man .git/config | awk -F/ '{print $NF}')

push () {
   git push ssh://$USER@review.pac-rom.com:29418/$PROJECT HEAD:refs/\for/$BRANCH
}

branch () {
   echo "Enter an option:"
   echo "   1. View your current branch"
   echo "   2. Enter a new current branch"
   read BRANCH
   case $BRANCH in
      1|1.)
         echo "Your current branch is: $(cat ~/.pac/branch)";;
      2|2.)
         echo "Enter your new current branch:"
         read BRANCH
         echo $BRANCH > ~/.pac/branch
         BRANCH=$(cat ~/.pac/branch)
         echo "Your new current branch is: $(cat ~/.pac/branch)";;
      *) echo "You did not choose a valid option (1 or 2)";;
   esac
}

name () {
   echo "Enter an option:"
   echo "   1. View your current gerrit username"
   echo "   2. Enter a new gerrit username"
   read NAME
   case $NAME in
      1|1.)
         echo "Your current gerrit username is: $(cat ~/.pac/username)";;
      2|2.)
         echo "Enter your new gerrit username:"
         read USER
         echo $USER > ~/.pac/username
         USER=$(cat ~/.pac/username)
         echo "Your new gerrit username is: $(cat ~/.pac/username)";;
      *) echo "You did not choose a valid option (1 or 2)";;
   esac
}

new () {
   cd ~/.pac
   curl http://pac-rom.com/downloads/pac-review > .new
   sed -e '12,132d' .new > .tmp
   NEWB=$(grep BUILD= .tmp | sed "s/BUILD=//g")
   NEWV=$(grep VERSION= .tmp | sed "s/VERSION=//g")
}

update () {
   new
   if [ $BUILD = "$NEWB" ]
   then
      echo "Already up to date (v$VERSION)"
   elif [ "$BUILD" -lt "$NEWB" ]
   then
      cp .new ~/bin/pac-review
      echo "Successfully updated to v$NEWV!"
   else
      echo "You Cheated!"
   fi
   rm .new .tmp
}

uf () {
   new
   cp .new ~/bin/pac-review
   rm .new
   echo "Forced update to v$NEWV!"
}

error () {
   echo " "
   echo "Please choose an option:"
   echo "   branch (b) --- View or edit your current branch"
   echo "   name   (n) --- View or edit your gerrit username"
   echo "   push   (p) --- Push to gerrit"
   echo "   update (u) --- Check for an update and download it if there is one available (use uf to force)"
   echo " "
   echo "If you encounter problems, check if:"
   echo "   1. Your gerrit username is correct (using the name option)"
   echo "   1. Your current branch is correct (using the branch option)"
   echo "   2. Your public ssh key is attached to your gerrit profile"
   echo " "
   echo "If you still encounter problems, ask on the official PAC-man forum at forum.pac-rom.com"
}

case $TYPE in
   b|branch)branch;;
   p|push)push;;
   n|name)name;;
   u|update)update;;
   uf)uf;;
   *)error;;
esac
