#!/bin/bash

###################################################################
#                                                                 #
# Created by Sniper/Goldflame09/wedgess/Papa Smurf151 for PAC-man #
#                                                                 #
###################################################################

VERSION=0.9
BUILD=9

set_up_user(){
if [ -f ${HOME}/.pac/username ]; then
   GUZER=`cat ${HOME}/.pac/username`
else
   echo -n "Please enter your Gerrit UserName: "; read GUZER
   echo "Your entered ${GUZER} is this correct"
   echo "Enter 1 for Yes or 2 for No"
   select correct1 in "Yes" "No"; do
   case ${correct1} in
        Yes ) mkdir -p ${HOME}/.pac;
              echo ${GUZER} > ${HOME}/.pac/username;
              echo "Your new gerrit username is: ${GUZER}"; break;;
        No ) echo -n "Re-Enter Gerrit UserName: "; read GUZER; echo; mkdir -p ${HOME}/.pac; echo ${GUZER} > ${HOME}/.pac/username; echo "Your new gerrit username is: ${GUZER}"; break;;
        *) clear; echo "Invalid Entry ${correct1}, Please enter a number between [1 - 2]"; echo; set_up_user; break;;
   esac
 done
fi
}


new_branch() {
   rm -f ${HOME}/.pac/branch
   echo "Please enter the branch you want to upload to:"
   echo "1 for CM-10.1"
   echo "2 for CM-10.2"
   echo "3 for GH-pages (for PAC PAPERS Only)"
   select correct3 in "Yes" "No"; do
     case ${select3} in
        1) BRANCH="cm-10.1"; break;;
        2) BRANCH="cm-10.2"; break;;
	3) BRANCH="gh-pages"; break;;
        *) clear; echo "Invalid Entry ${correct3}, Please enter a number between [1 - 3]"; echo; new_branch; break;;
     esac
   done
   echo ${BRANCH} > ${HOME}/.pac/branch
   BRANCH=`cat ${HOME}/.pac/branch`
   echo "Your new current branch is: ${BRANCH}"
}

correct_commit() {
clear; echo ${MSSG}; echo
echo "Is this correct ??"
echo "Enter 1 for Yes and 2 for No"
  select correct2 in "Yes" "No"; do
   case ${correct2} in
	Yes ) echo "Commit set to ${MSSG}"; break;;
	No ) echo "Re-enter commit message"; read MSSG; break;;
	* ) clear; echo "Invalid Entry ${correct2}, Please re-try"; echo; echo; correct_commit; break ;;
   esac
  done
}

ap () {
git add -A
scp -p -P 29418 ${GUZER}@review.pac-rom.com:hooks/commit-msg .git/hooks/
   echo "Add commit message below.
--------------------------"
   read MSSG
   correct_commit
git commit -a -m "${MSSG}"
echo -n "Are you ready to push? (y/n): "; read RESPi
push   
}


push () {
echo -n "Are you sure you want to push? (y/n): "; read RESP
if [ "${RESP}" == "y" ] || [ "${RESP}" == "Y" ]; then
	if [ -f ${HOME}/.pac/branch ]; then
  	  echo "Current branch: `cat ${HOME}/.pac/branch`"
  	  echo -n "Push to current branch? (y/n): "; read CTPUSH
  		if [ "${CTPUSH}" == "y" ] || [ "${CTPUSH}" == "Y" ]; then
			BRANCH=`cat ${HOME}/.pac/branch`
  		else
			new_branch
  		fi
	else
	  new_branch
	fi
    PROJECT=`grep PAC-man .git/config | awk -F/ '{print $NF}'`
    git push ssh://${GUZER}@review.pac-rom.com:29418/${PROJECT} HEAD:refs/\for/${BRANCH}
else
  echo "Canceled"
fi
}


amend () {
   echo -n "Have you edited the files?/Do you want to change commit message? (y/n):"; read RESPa
if [ "${RESPa}" == "y" ] || [ "${RESPa}" == "Y" ]; then
   git add -A
   git commit --amend
   push
elif [ "${RESPa}" == "n" ] || [ "${RESPa}" == "N" ]; then
	echo "Please edit them"
	echo "Press 1 after you edit them"
	read amend1
	if [ ${amend1} == "1" ]; then
		git add -A
		git commit --amend
		push
	else
		echo "Take your time and come back when you are ready"
	fi
fi
}


correct_gname() {
echo "Your entered ${GUZER} is this correct?"
echo "Enter 1 for Yes and 2 for No"
   select correct1 in "Yes" "No"; do
   case ${correct1} in
	Yes ) mkdir ${HOME}/.pac; echo ${GUZER} > ${HOME}/.pac/username; echo "Your new gerrit username is: ${GUZER}"; break;;
	No ) echo -n "Re-Enter Gerrit UserName: "; read GUZER; break;;
	* ) clear; echo "Invalid Entry ${correct1}, Please re-try"; echo; echo; correct_gname break ;;
   esac
  done
}


nameq_question() {
  select NAME in "View" "New"; do
   case ${NAME} in
      View ) if [ -f ${HOME}/.pac/username ]; then
           echo "Your current gerrit username is: ${GUZER}";
	  else
	   echo "No gerrit username found..";
	  fi; break;;
      New ) echo -n "Enter your new gerrit username: "; read GUZER; correct_gname; break;;
      * ) clear; echo "${NAME} is not a valid option (Choose 1 or 2)"; nameq_question; break;;
   esac
  done
}


name () {
   echo "Enter an option:"
   echo "   1. View your current gerrit username"
   echo "   2. Enter a new gerrit username"
   echo; nameq_question
}


sshkey () {
if [ -e ${HOME}/.ssh/id_rsa.pub ]; then
   echo "SSH Key already exists.

Go to PAC Gerrit (http://review.pac-rom.com), sign in, go to settings, 
and click on SSH Public Keys. Use Control + Click to open URL.

Click on add SSH Key and copy and paste contents of file from .ssh/id_rsa.pub."
read -p "Press [Enter] to open file..."
   gnome-open ${HOME}/.ssh/id_rsa.pub
else
   ssh-keygen
   echo "Go to PAC Gerrit (http://review.pac-rom.com), sign in, go to settings, 
and click on SSH Public Keys. Use Control + Click to open URL.

Click on add SSH Key and copy and paste contents of file from .ssh/id_rsa.pub."
read -p "Press [Enter] to open file..."
   gnome-open ${HOME}/.ssh/id_rsa.pub
fi
}


new () {
   curl http://pac-rom.com/downloads/pac-review > ${HOME}/.pac/.new
   sed -i '12,132d' ${HOME}/.pac/.new
   NEWB=`grep BUILD= ${HOME}/.pac/.new | sed "s/BUILD=//g"`
   NEWV=`grep VERSION= ${HOME}/.pac/.new | sed "s/VERSION=//g"`
}

ask_the_question() {
echo -n "Are you sure you want to update to version: ${NEWV} build: ${NEWB}? (yes/no)"
select correct4 in "Yes" "No"; do
  case ${correct4} in
      Yes ) rm -f ${HOME}/.pac/pac-review; mv ${HOME}/.pac/.new ${HOME}/bin/pac-review; chmod +x ${HOME}/bin/pac-review; echo; echo "Successfully updated to v${NEWV}!"; break;;
      No ) echo "Update canceled"; break ;;
      * ) clear; echo "Invalid option ${correct4}, Please try again..."; echo; ask_the_question; break;;
   esac
done
}

update () {
   new
   if [ "${BUILD}" == "${NEWB}" ]; then
      echo; echo "Already up to date (v${VERSION})"
   elif [[ "${BUILD}" != "${NEWB}" ]]; then
      ask_the_question
fi
}

uf () {
   new
   mv ${HOME}/.pac/.new ${HOME}/bin/pac-review
   chmod +x ${HOME}/bin/pac-review
   echo "Forced update to v${NEWV}!"
}

error () {
   echo " "
   echo "Usage: pac-review [-short command]"
   echo "Or:    pac-review [long comand]"
   echo " "
   echo "Commands:"
   echo "   add+push   	(-ap)  --- Add and push to gerrit"
   echo "   amend  	(-am)  --- Amend the commit and push"
   echo "   force	(-uf)  --- Force the script to grab a new version"
   echo "   name   	(-n)   --- View or edit your gerrit username"
   echo "   branch	(-nb)  --- Choose a new branch to push to"
   echo "   push   	(-p)   --- Push to gerrit"
   echo "   sshkey 	(-ssh) --- Create/show SSH key to put on Gerrit"
   echo "   update 	(-u)   --- Check for, and download an update if one is available"
   echo " "
   echo "If you encounter problems, check if:"
   echo "   1. Your gerrit username is correct (using the name option)"
   echo "   2. Your current branch is correct"
   echo "   3. Your public ssh key is attached to your gerrit profile"
   echo " "
   echo "If you still encounter problems, ask on the official PAC-man forum at:"
   echo "http://forum.pac-rom.com . . . . Press Control + Click to open URL"
   echo " "

}


if [ ! -d ${HOME}/bin ]; then
 mkdir -p ${HOME}/bin
 echo "# Add ~/bin to PATH" >> ${HOME}/.bashrc
 echo "export PATH=${PATH}:~/bin" >> ${HOME}/.bashrc
fi

set_up_user

case $1 in
   -n|name)name;;
   -nb|branch)new_branch;;
   -u|update)update;;
   -p|push)push;;
   -ssh|sshkey)sshkey;;
   -ap|add+push)ap;;
   -am|amend)amend;;
   -uf|force)uf;;
   -h|help|*)error;;
esac
