#!/bin/bash

#############################################
#                                           #
# Created by Sniper/Goldflame09 for PAC-man #
#                                           #
#############################################

VERSION=0.9
BUILD=9

if [ -e ~/.pac/username ]
then
   USER=$(cat ~/.pac/username)
else
   echo "Please enter your gerrit username:"
   read USER
   mkdir ~/.pac
   echo $USER > ~/.pac/username
   USER=$(cat ~/.pac/username)
   echo "Your new gerrit username is: $(cat ~/.pac/username)"
fi

TYPE="$1"
push () {
 read -p "Are you sure? (y/n) " RESP
if [ "$RESP" = "y" ]; then
   rm -rf ~/.pac/branch
   echo "Please enter the branch you want to upload to (ex. cm-10.2):"
   read BRANCH
   echo $BRANCH > ~/.pac/branch
   BRANCH=$(cat ~/.pac/branch)
   echo "Your new current branch is: $(cat ~/.pac/branch)"

PROJECT=$(grep PAC-man .git/config | awk -F/ '{print $NF}')

   git push ssh://$USER@review.pac-rom.com:29418/$PROJECT HEAD:refs/\for/$BRANCH
else
  echo "Canceled"
fi
}
name () {
   echo "Enter an option:"
   echo "   1. View your current gerrit username"
   echo "   2. Enter a new gerrit username"
   read NAME
   case $NAME in
      1|1.)
         echo "Your current gerrit username is: $(cat ~/.pac/username)";;
      2|2.)
         echo "Enter your new gerrit username:"
         read USER
         echo $USER > ~/.pac/username
         USER=$(cat ~/.pac/username)
         echo "Your new gerrit username is: $(cat ~/.pac/username)";;
      *) echo "You did not choose a valid option (1 or 2)";;
   esac
}

new () {
   cd ~/.pac
   curl http://pac-rom.com/downloads/pac-review > .new
   sed -e '12,132d' .new > .tmp
   NEWB=$(grep BUILD= .tmp | sed "s/BUILD=//g")
   NEWV=$(grep VERSION= .tmp | sed "s/VERSION=//g")
}

update () {
   new
   if [ $BUILD = "$NEWB" ]
   then
      echo "Already up to date (v$VERSION)"
   elif [ "$BUILD" -lt "$NEWB" ]
   then
      cp .new ~/bin/pac-review
      echo "Successfully updated to v$NEWV!"
   else
      echo "You Cheated!"
   fi
   rm .new .tmp
}

uf () {
   new
   cp .new ~/bin/pac-review
   rm .new
   echo "Forced update to v$NEWV!"
}

error () {
   echo " "
   echo "Please choose an option:"
   echo "   name   (-n) --- View or edit your gerrit username"
   echo "   update (-u) --- Check for an update and download it if there is one available (use uf to force)"
   echo "   push   (-p) --- Push to gerrit"
   echo " "
   echo "If you encounter problems, check if:"
   echo "   1. Your gerrit username is correct (using the name option)"
   echo "   1. Your current branch is correct"
   echo "   2. Your public ssh key is attached to your gerrit profile"
   echo " "
   echo "If you still encounter problems, ask on the official PAC-man forum at forum.pac-rom.com"
}

case $TYPE in
   -n|name)name;;
   -u|update)update;;
   -p|push)push;;
   *|help)error;;
   -h|help)error;;
   -help|help)error;;
   -uf)uf;;
esac
